### ISSUE TITLE
bug: kitty-scrollback.nvim hangs after kitten ssh (blank screen after ssh)

### ISSUE THREAD

**Issue by ismasou** [mikesmithgh/kitty-scrollback.nvim#99] opened 2023-12-11 11:36 UTC
Thank you for the plugin. 
I really wanted a vi mode in scroll back. 
It seems to work well for me for local commands, but if I enter an ssh server, neovim is blank in scrollback mode.
Has anybody tried in ssh?
Using the default less works fine in ssh.

**Comment by mikesmithgh** [comment] 2023-12-11 12:01
Hey @ismasou, thanks for reporting.

I have successfully used it over ssh. Could you provide some steps to reproduce or a video/screenshot?

Also, could you provide the output of `:KittyScrollbackCheckHealth` ? This will help me get information about your setup.

**Comment by mikesmithgh** [comment] 2023-12-11 12:21
@ismasou , I just pushed a fix for that a few minutes ago 🙂. Could you pull latest and try again for the checkhealth?

**Comment by mikesmithgh** [comment] 2023-12-12 12:19
@ismasou interesting, I just tried with `kitten ssh` and aliasing `ssh` to `kitten ssh` and didn't have any issues. Do you have any extra configs around `kitten ssh` that you can share?

**Comment by skrobul** [comment] 2023-12-13 10:13
I am hitting the same problem when I use the `kitten ssh` which unfortunately I need to do every time on some destinations that have ephemeral home directories.

[Here](https://gist.github.com/skrobul/7801f02517a4c3bff8806e2f39d3df33) is my `:KittyScrollbackCheckHealth`. 

Screenshot below, although it's a bit useless:
![image](https://github.com/mikesmithgh/kitty-scrollback.nvim/assets/183976/a0de67d9-99cc-4345-8e4a-170034291371).

If I press `i`, it changes to this:
![image](https://github.com/mikesmithgh/kitty-scrollback.nvim/assets/183976/8d95311c-3faf-4bfd-bfa1-49fefb01ec65)

Finally, to exit out of this I press Escape twice and get slightly better error message:
![image](https://github.com/mikesmithgh/kitty-scrollback.nvim/assets/183976/5a05cce8-0256-478f-b4f6-3bdf38b1b792)

Here is my [kitty.conf](https://github.com/skrobul/dotfiles/blob/a0aea2b3b0b04349d43e2ed71ecd58f89d7290b2/config/kitty/kitty.conf) from the time the screenshots were taken.
 
ps. just to confirm, it works without `kitten`.

**Comment by mikesmithgh** [comment] 2023-12-13 13:47
@skrobul thanks for the info, that was helpful. I was finally able to reproduce using Linux, I couldn't reproduce on a Mac. I'll dig into this

**Comment by mikesmithgh** [comment] 2023-12-13 20:37
Hey @skrobul and @ismasou thank you for reporting the issue, I have investigated a bit on my end and think I have it working. Would you mind testing with the branch `troubleshoot-kitty-ssh` https://github.com/mikesmithgh/kitty-scrollback.nvim/pull/113.

The problem seems to go away when I unset the environment variable `KITTY_KITTEN_RUN_MODULE`. I need to further investigate the impact of this, but this looks to be used around `ssh_askpass`. I don't think it should impact anything since it is only modified in the scope of kitty-scrollback.nvim.

Please let me know if it works and if you discover any other issues. I don't use `kitten ssh` that often (although I may start to now 😹) so you may know of some other edge cases that I am not aware of.

**Comment by skrobul** [comment] 2023-12-14 12:50
> Would you mind testing with the branch troubleshoot-kitty-ssh https://github.com/mikesmithgh/kitty-scrollback.nvim/pull/113.

After checking out [a3c152a](https://github.com/mikesmithgh/kitty-scrollback.nvim/commit/a3c152ae7e737cd353b47c72d6f88a3ae8b0e8b0) the problem is resolved for me, thank you very much !

**Comment by mikesmithgh** [comment] 2023-12-14 16:20
@skrobul awesome! merged 😸

**Closed by mikesmithgh** 2023-12-14 16:20 UTC
Labels: bug
