### ISSUE TITLE
bug: KittyScrollbackCheckHealth hangs and unable to specify runtimepath with custom config

### ISSUE THREAD

**Issue by steakhutzeee** [mikesmithgh/kitty-scrollback.nvim#270] opened 2024-09-08 16:58 UTC
Hi, I just installed the plugin and look it's working mostly fine. 

Noted a few points:

1. `nvim +'KittyScrollbackCheckHealth'` does not work for me.

Kitty just hangs, becoming unresponsive.

Any idea why? Opening nvim and checking health from there with `:checkhealth kitty` finds nothing.

2. Also, I noted that if I setup my config with `global = function()` then I still have to use `--config global` in my kitty.conf, like 'global' is not recognized as the actual global config.

3. I managed to apply my custom keymaps defining them in a custom config via `custom_config = function()` and `--config custom_config` in my kitty.conf. Then I created an empty lua file with `vim.opt.runtimepath:append(vim.fn.stdpath('data') .. '/lazy/kitty-scrollback.nvim')` in it and appended `--nvim-args -u /lua file`. I tested opening nvim with -u option and pointing to this lua file and it opens without issue. But when I open the scrollback then I receive an error that it's unable to read my custom_config. Ideas why?

Thanks!

**Comment by mikesmithgh** [comment] 2024-10-01 13:36
> Opening nvim and checking health from there with :checkhealth kitty finds nothing.

This should be `checkhealth kitty-scrollback`

> Any idea why?

Most likely there is some lazy loading going on and kitty-scrollback.nvim is not loaded yet. Could you share you configuration for kitty-scrollback.nvim?

I'm not sure if you are using lazy.nvim, but for example in the README https://github.com/mikesmithgh/kitty-scrollback.nvim/blob/d51725a6b71d65dd9df83ddc07903de2fb2736ee/README.md?plain=1#L241

You have to specify the `cmd` to automatically load kitty-scrollback.nvim for `KittyScrollbackCheckHealth`.

```lua
  {
    'mikesmithgh/kitty-scrollback.nvim',
    enabled = true,
    lazy = true,
    cmd = { 'KittyScrollbackGenerateKittens', 'KittyScrollbackCheckHealth' },
    event = { 'User KittyScrollbackLaunch' },
    -- version = '*', -- latest stable version, may have breaking changes if major version changed
    -- version = '^5.0.0', -- pin major version, include fixes and features that do not have breaking changes
    config = function()
      require('kitty-scrollback').setup()
    end,
  }
```

> I managed to apply my custom keymaps defining them in a custom config via custom_config = function() and --config custom_config in my kitty.conf. Then I created an empty lua file with vim.opt.runtimepath:append(vim.fn.stdpath('data') .. '/lazy/kitty-scrollback.nvim') in it and appended --nvim-args -u /lua file. I tested opening nvim with -u option and pointing to this lua file and it opens without issue. But when I open the scrollback then I receive an error that it's unable to read my custom_config. Ideas why?

I'm not quite sure. Could you provide your Neovim and kitty.conf configuration so I can take a look?

**Comment by steakhutzeee** [comment] 2024-10-01 16:56
Sure, here is my nvim kitty-scrollback config https://gist.github.com/steakhutzeee/92afb11bc18d0b97b5bb9ba029136600 and here is my Kitty config https://gist.github.com/steakhutzeee/e65233d3e61069fbce2b1bc69e369862

Thanks!

**Comment by mikesmithgh** [comment] 2024-10-01 20:47
Your config appears fine to me, at least I can't see anything that would be a problem.

> Also, manually entering the checkhealth as indicated I get:
> ERROR No healthcheck found for "kitty-scrollback" plugin.

This makes sense since it is lazy loaded and hasn't loaded yet.

Try opening neovim and running
```
:lua require('kitty-scrollback')
checkhealth kitty-scrollback
```

This should at least give you some healthcheck (not the full one since it isn't ran with `:KittyScrollbackCheckHealth`). Let me know if that atleast works then will continue trying to troubleshoot.


> I managed to apply my custom keymaps defining them in a custom config via custom_config = function() and --config custom_config in my kitty.conf. Then I created an empty lua file with vim.opt.runtimepath:append(vim.fn.stdpath('data') .. '/lazy/kitty-scrollback.nvim') in it and appended --nvim-args -u /lua file. I tested opening nvim with -u option and pointing to this lua file and it opens without issue. But when I open the scrollback then I receive an error that it's unable to read my custom_config. Ideas why?


I'm a little confused by this. Your config looked okay. 

Are you saying you did:
1. added custom_config to you kitty-scrollback.nvim config and --config custom_config in my kitty.conf
2. it worked successfully?
3. if so why did you create the other lua file and do `--nvim-args -u /lua file` ?

You may be combining two approached. Are you trying to follow https://github.com/mikesmithgh/kitty-scrollback.nvim?tab=readme-ov-file#user-configuration to have a separate nvim configuration?

**Comment by steakhutzeee** [comment] 2024-10-10 00:00
Quite busy at work these days. Will check ASAP.

**Comment by mikesmithgh** [comment] 2024-10-10 11:13
> Quite busy at work these days. Will check ASAP.

No worries. Same 😅

**Comment by steakhutzeee** [comment] 2024-10-11 20:49
So here is the output of 
```
:lua require('kitty-scrollback')
checkhealth kitty-scrollback
```


```
==============================================================================
kitty-scrollback: require("kitty-scrollback.health").check()

kitty-scrollback: Neovim version 0.9+ ~
- OK NVIM 0.10.2

kitty-scrollback: kitty-scrollback.nvim version ~
- OK        `|`\___/`|`       *kitty-scrollback.nvim* @ `v5.0.1`
           =) `^`Y`^` (=
            \  *^*  /       If you have any issues or questions using *kitty-scrollback.nvim* then     
            ` )=*=( `       please create an issue at                                                    
            /     \       https://github.com/mikesmithgh/kitty-scrollback.nvim/issues and              
            |     |       provide the `KittyScrollbackCheckHealth` report.                               
           /| | | |\                                                                                    
           \| | `|`_`|`/\
            /_// ___/     *Bonus* *points* *for* *cat* *memes*
               \_)       

kitty-scrollback: Kitty remote control ~
- OK `kitty @ ls` exited with code *0*

kitty-scrollback: Kitty data ~
- WARNING No Kitty data available unable to perform a complete healthcheck
  - ADVICE:
    - If you ran `:checkhealth` or `:checkhealth kitty-scrollback` then this WARNING is expected
    - Execute the command `:KittyScrollbackCheckHealth` for a complete healthcheck
```

Yes, I was trying to run kitty-scrollback in an nvim config that only runs this plugin. So, if I use a separate .lua file as explained here https://github.com/mikesmithgh/kitty-scrollback.nvim?tab=readme-ov-file#user-configuration then the config should go there instead of my standard configuration file I posted above for kitty-scrollback?

**Comment by steakhutzeee** [comment] 2024-10-15 17:34
Also, another question. Here https://github.com/mikesmithgh/kitty-scrollback.nvim/issues/152#issuecomment-1879899211 I read 

`After you do that, it still won't pick up though because by default kitty-scrollback.nvim runs nvim with the arguments --clean --noplugin -n which prevents nvim from loading any plugins. So, it won't load your lazy config. To get around this you can specify the argument --no-nvim-args and no arguments will be passed to nvim.
`
So why it is working for me with a custom config name and using` --nvim-args --clean --noplugin -n`?

**Comment by mikesmithgh** [comment] 2024-11-01 18:41
Hey @steakhutzeee sorry for the delay in getting back to you.

`by default kitty-scrollback.nvim runs nvim with the arguments --clean --noplugin -n which prevents nvim from loading any plugins` is no longer the case. In previous versions of kitty-scrollback.nvim those were passed by default, they are no longer passed by default.

> So why it is working for me with a custom config name and using --nvim-args --clean --noplugin -n?

It shouldn't, could you show me the full command you have? Are you passing any other parameters?

**Comment by mikesmithgh** [comment] 2024-11-01 18:47
@steakhutzeee 
> Maybe the lack of color for the selection is that I'm missing in loading my Neovim theme in both of the solutions? I don't know, I use the same theme, tokyonight also for Kitty, so I would expect for it to work automatically.

There is an option to customize the visual selection coloring:
```
  -- string? Sets the mode for coloring the Visual highlight group in the scrollback buffer window. darken uses a darkened version of the Normal highlight group to improve readability. kitty uses the colors defined for selection_foreground and selection_background in your Kitty configuration. nvim uses the default colors defined in the Visual highlight group. reverse reverses the foreground and background colors of the visual selection.
  visual_selection_highlight_mode = 'darken',
```

This was introduced in https://github.com/mikesmithgh/kitty-scrollback.nvim/issues/32

You may have to tweak that option for your setup.

**Comment by mikesmithgh** [comment] 2024-11-01 19:06
I am reading through this, and I am thinking there may be some confusion and I might have missed what you were asking about global at the start.

Here https://github.com/mikesmithgh/kitty-scrollback.nvim/issues/152#issuecomment-1879899211
I mentioned 
> With global it would look like this
>
> ```lua
> require('kitty-scrollback').setup({
>  global = function()
>    return { keymaps_enabled = false }
>  end,
> })
> ```

That is actually no longer a valid config name (it was in older versions of kitty-scrollback.nvim).

See https://github.com/mikesmithgh/kitty-scrollback.nvim?tab=readme-ov-file#global-configuration

The global configuration is just the first entry in the table without a key.


> global | Global options that apply to all builtin and user defined configurations. The first element in the options table without a key is considered the global options.


It would look something like this:
```lua
require('kitty-scrollback').setup({
    -- global configuration
    {
      status_window = {
        autoclose = true,
      },
    },
    -- builtin configuration override
    ksb_builtin_get_text_all = {
      kitty_get_text = {
        ansi = false,
      },
    },
    -- user defined configuration table
    myconfig = {
      kitty_get_text = {
        ansi = false,
      },
    },
    -- user defined configuration function
    myfnconfig = function(kitty_data)
      return {
        kitty_get_text = {
          extent = (kitty_data.scrolled_by > kitty_data.lines) and 'all' or 'screen',
        },
      }
    end,
})
```

So let me take a step back to make sure I understand the problem correctly. You would like to have a separate dedicated kitty-scrollback.nvim configuration from your Neovim configuration and preferably only use one file instead of two? Did I get it right?

**Comment by steakhutzeee** [comment] 2024-11-01 19:37
Yes that is the desired outcome, one file.

Actually the full nvim kitty-scrollback is the one from above https://gist.github.com/steakhutzeee/92afb11bc18d0b97b5bb9ba029136600 and this is what I have in my kitty config:

```
# Required by kitty-scrollback
allow_remote_control socket-only
listen_on unix:/tmp/kitty

# kitty-scrollback.nvim Kitten alias
action_alias kitty_scrollback_nvim kitten $HOME/.local/share/nvim/lazy/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py --config custom_config --nvim-args --clean --noplugin -n #--nvim-args -u $HOME/.config/nvim/kitty-scrollback-nvim-kitten-config.lua

# Browse scrollback buffer in nvim
map kitty_mod+f kitty_scrollback_nvim
# Browse output of the last shell command in nvim
map kitty_mod+g kitty_scrollback_nvim --config ksb_builtin_last_cmd_output
# Show clicked command output in nvim
mouse_map ctrl+shift+right press ungrabbed combine : mouse_select_command_output : kitty_scrollback_nvim --config ksb_builtin_last_visited_cmd_output

```

As you say, this should not work by using `scrollback.nvim/python/kitty_scrollback_nvim.py --config custom_config --nvim-args --clean --noplugin -n` but it does for me.

Ok, I will try the settings for the color problem.

About the use of 'global', yes I read the docs and that's why I'm using 'custom_config' as a name. I tried without it, without any name actually, in order to append the global config, but as said at the start it does not work. My config only works using a custom config name.

**Comment by mikesmithgh** [comment] 2024-11-02 00:16
> As you say, this should not work by using `scrollback.nvim/python/kitty_scrollback_nvim.py --config custom_config --nvim-args --clean --noplugin -n` but it does for me.

Ah I see what is going on.

From https://sw.kovidgoyal.net/kitty/conf/

> Comments can be added to the config file as lines starting with the # character. This works only if the # character is the first character in the line.

You have a comment at the end of the line:
```
action_alias kitty_scrollback_nvim kitten $HOME/.local/share/nvim/lazy/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py --config custom_config --nvim-args --clean --noplugin -n #--nvim-args -u $HOME/.config/nvim/kitty-scrollback-nvim-kitten-config.lua
```

When kitty-scrollback.nvim parses it, it takes everything after the first `--nvim-args` and treats it like if you ran nvim like this:

```
nvim --clean --noplugin -n '#--nvim-args' -u /Users/mike/.config/nvim/kitty-scrollback-nvim-kitten-config.lua
```

This is treating `#--nvim-args' as a filename, and then also including the last part `-u /Users/mike/.config/nvim/kitty-scrollback-nvim-kitten-config.lua`

**Comment by mikesmithgh** [comment] 2024-11-02 01:19
@steakhutzeee 

I have an example configuration that you can use as a reference. In this case, it uses the `KITTY_SCROLLBACK_NVIM` environment variable to determine the behavior of the `kitty-scrollback.nvim` file. If `KITTY_SCROLLBACK_NVIM` is `true` then you can treat it as a minimal configuration for kitty-scrollback.nvim, otherwise it serves as lazy.nvim's plugin configuration.

`~/.config/nvim/lua/plugins/kitty-scrollback-nvim.lua`
```lua
local kitty_scrollback_config = function()
  require('kitty-scrollback').setup({
    -- global config
    {
      visual_selection_highlight_mode = 'reverse',
      callbacks = {
        after_ready = function()
          vim.defer_fn(function()
            vim.notify('\nThis is a global config', vim.log.levels.WARN, {})
          end, 1000)
        end,
      },
    },
    search = {
      callbacks = {
        after_ready = function()
          vim.defer_fn(function()
            vim.api.nvim_feedkeys('?', 'n', false)
          end, 100)
        end,
      },
    },
  })
end

if vim.env.KITTY_SCROLLBACK_NVIM == 'true' then
  -- kitty-scrollback.nvim minimal config
  vim.opt.runtimepath:append(vim.fn.stdpath('data') .. '/lazy/kitty-scrollback.nvim') -- lazy.nvim
  vim.g.mapleader = ' '
  vim.g.maplocalleader = ','
  vim.cmd.colorscheme('zaibatsu')
  kitty_scrollback_config()
  return {}
else
  -- kitty-scrollback.nvim lazy.nvim config
  return {
    {
      'mikesmithgh/kitty-scrollback.nvim',
      enabled = true,
      lazy = true,
      cmd = { 'KittyScrollbackGenerateKittens', 'KittyScrollbackCheckHealth' },
      event = { 'User KittyScrollbackLaunch' },
      config = kitty_scrollback_config,
    },
  }
end
```

`~/.config/kitty/kitty.conf`
```
action_alias kitty_scrollback_nvim kitten $HOME/.local/share/nvim/lazy/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py --nvim-args -u $HOME/.config/nvim/lua/plugins/kitty-scrollback-nvim.lua

map kitty_mod+h kitty_scrollback_nvim
```


https://github.com/user-attachments/assets/020a63da-e373-4834-8d23-44c09aa620ef

Please let me know if that works for you or if you hit any other issues.

**Comment by steakhutzeee** [comment] 2024-11-02 10:14
Thank you for the config. Tho I'm trying to adapt it to my setup, as I use a combination of:

```
local M

function M.config()

return M
```

https://gist.github.com/steakhutzeee/92afb11bc18d0b97b5bb9ba029136600

**Comment by mikesmithgh** [comment] 2024-11-04 13:51
@steakhutzeee 
> For it to work I also added vim.opt.runtimepath:append(vim.fn.stdpath('data') .. '/lazy/tokyonight.nvim') to the config but this way when I run the scrollback the screen looks a lot brighter, then when I close it, it returns to normal.

You may not need to set the colorscheme, I was just adding an example. How does it look if you don't set it?

> (is it ok the way I configured my keymaps?)

You should move those mappings outside of the config itself. Like this:

```lua
local kitty_scrollback_config = function()
  -- https://github.com/mikesmithgh/kitty-scrollback.nvim/issues/152
  vim.keymap.set({ 'v' }, 'Y', '<Plug>(KsbVisualYankLine)', {})
  vim.keymap.set({ 'v' }, 'y', '<Plug>(KsbVisualYank)', {})
  vim.keymap.set({ 'n' }, 'Y', '<Plug>(KsbNormalYankEnd)', {})
  vim.keymap.set({ 'n' }, 'y', '<Plug>(KsbNormalYank)', {})
  vim.keymap.set({ 'n' }, 'yy', '<Plug>(KsbYankLine)', {})
  require('kitty-scrollback').setup({
    {
      visual_selection_highlight_mode = 'kitty',
    },
  })
end
```

> Note that still with this configuration Kitty waits and then hangs trying to load the health checks, same as I was saying in my first post. Tried the exact command you use in the video above, as it appears in the cmd section of the config.

This is odd. Could you show a video? If you wait around 20 seconds does anything show? Or if you press ctrl+c? 

> Side question, how is that your cursor moves that way? Is it just a video effect?

Kitty had a recent release `v0.37.0` that allows cursor trail animations! Check out this PR https://github.com/kovidgoyal/kitty/pull/7970 and config: https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.cursor_trail

I have mine set to
```
cursor_trail 3
cursor_trail_decay 0.2 0.3
cursor_trail_start_threshold 3
```

**Comment by steakhutzeee** [comment] 2024-11-04 16:58
> @steakhutzeee
> 
> > For it to work I also added vim.opt.runtimepath:append(vim.fn.stdpath('data') .. '/lazy/tokyonight.nvim') to the config but this way when I run the scrollback the screen looks a lot brighter, then when I close it, it returns to normal.
> 
> You may not need to set the colorscheme, I was just adding an example. How does it look if you don't set it?
> 

Without setting the theme it looks good apart from the bottom bar when it's invoked with ":". that is not colored, but is a minor thing. The brightness issue does not happens.

**Comment by steakhutzeee** [comment] 2024-11-04 17:00
> This is odd. Could you show a video? If you wait around 20 seconds does anything show? Or if you press ctrl+c?
> 
 It just waits forever loading the health check in question, until whole kitty changes color to grey and became unresponsive and I have to kill it.

**Comment by mikesmithgh** [comment] 2024-11-14 04:49
Hey @steakhutzeee 

I just merged a fix to main. Could you pull the latest changes on main and retry `:KittyScrollbackCheckHealth` ?

I noticed some failures on CI tests which I could not reproduce locally. It appears that Kitty was crashing when I attempted to get debug information during checkhealth. I removed those checks from checkhealth and CI runs are successful again.

**Comment by steakhutzeee** [comment] 2024-11-14 15:40
Sorry for the delay, will try asap.

**Comment by steakhutzeee** [comment] 2024-11-14 18:31
> Hey @steakhutzeee
> 
> I just merged a fix to main. Could you pull the latest changes on main and retry `:KittyScrollbackCheckHealth` ?
> 
> I noticed some failures on CI tests which I could not reproduce locally. It appears that Kitty was crashing when I attempted to get debug information during checkhealth. I removed those checks from checkhealth and CI runs are successful again.

Look it works but the buffer with the healthcheck closes immediately upon completion.

**Comment by mikesmithgh** [comment] 2024-11-14 20:17
Interesting. 

> Look it works but the buffer with the healthcheck closes immediately upon completion.

- Do you actually see any of the result of checkhealth before it closes? 
- Does `:messages` have any information?

> So after the healthcheck closes automatically I have to close my file two times to exit nvim

This is kind of expected. `:KittyScrollbackCheckHealth` opens a kitty overlay window over your current window and runs the checkhealth command in nvim. So, when you close the checkhealth it is closing another instance of Kitty/nvim.

This is what I would expect for example:

https://github.com/user-attachments/assets/2b1e9659-9c51-4a79-8737-b3321186257a

**Comment by mikesmithgh** [comment] 2024-11-14 23:45
> Found out that the problem could be the neovim-session-manager plugin, if I open nvim in a dir I never opened nvim in, then I can see the result of the healtcheck just fine:

@steakhutzeee ah good catch!


I've seen issues with similar session manager plugins before like auto-session. I have some info on disabling that one here https://github.com/mikesmithgh/kitty-scrollback.nvim/wiki#auto-session. 

I'll see if I can reproduce with neovim session manager and add a note. I probably need a better place to put the info or some troubleshooting steps so that it is obvious.

**Comment by mikesmithgh** [comment] 2024-11-14 23:46
@steakhutzeee also thanks for sticking with me on debugging this 😄

**Comment by mikesmithgh** [comment] 2024-11-15 01:22
@steakhutzeee 

I was able to reproduce the issue and recommend to add a check to `autoload_mode` in neovim-session-manager's setup. If `vim.env.KITTY_SCROLLBACK_NVIM` is set then disable autoloading, otherwise set it to your preferred mode (default is LastSession).

For example:

```lua
return {
  {
    'Shatur/neovim-session-manager',
    event = 'VimEnter',
    config = function()
      local modes = require('session_manager.config').AutoloadMode
      require('session_manager').setup({
        autoload_mode = vim.env.KITTY_SCROLLBACK_NVIM == 'true' and modes.Disabled or modes.LastSession,
      })
    end,
  },
}
```

https://github.com/user-attachments/assets/021b6741-96b5-43ac-b63e-8ffe7fec2ba6


Please let me know if this works or if you hit any other issues.

**Comment by steakhutzeee** [comment] 2024-11-15 16:50
Tried the following but did not work:

```
local M = {
  "Shatur/neovim-session-manager",
  event = "VimEnter"
}

function M.config()

  local config = require('session_manager.config')

  require("session_manager").setup {
    autoload_mode = { vim.env.KITTY_SCROLLBACK_NVIM == 'true' and config.AutoloadMode.Disabled or config.AutoloadMode.LastSession, config.AutoloadMode.CurrentDir }
  }
end

return M
```

Also, since I use `AutoloadMode.CurrentDir`, could I just do:

`autoload_mode = { vim.env.KITTY_SCROLLBACK_NVIM == 'true' and config.AutoloadMode.Disabled, config.config.AutoloadMode.CurrentDir } 

since the plugin supports it:

> autoload_mode can be set to either a single mode or an array of modes, in which case each mode will be tried until one succeeds.

**Comment by steakhutzeee** [comment] 2024-11-16 17:04
Worked fine, thank you!

**Comment by steakhutzeee** [comment] 2024-11-16 17:05
> @steakhutzeee also thanks for sticking with me on debugging this 😄

It's been a pleasure! It's fantastic to "meet" someone who share the love to troubleshoot problems!!

**Comment by mikesmithgh** [comment] 2024-11-19 20:10
I've added the info to the wiki https://github.com/mikesmithgh/kitty-scrollback.nvim/wiki#neovim-session-manager and updated README to include:

> [!IMPORTANT]\
> Please review the [Recommended Configurations for other plugins](https://github.com/mikesmithgh/kitty-scrollback.nvim/wiki#recommended-configurations-for-other-plugins) 
> section of the wiki to prevent conflicts with other plugins.

> It's been a pleasure! It's fantastic to "meet" someone who share the love to troubleshoot problems!!

@steakhutzeee thanks you too! let me know if you hit any other issues

**Closed by mikesmithgh** 2024-11-19 20:10 UTC
Labels: bug
