### ISSUE TITLE
bug: failure to open over kitten ssh

### ISSUE THREAD

**Issue by SichangHe** [mikesmithgh/kitty-scrollback.nvim#221] opened 2024-04-04 06:51 UTC
![image](https://github.com/mikesmithgh/kitty-scrollback.nvim/assets/84777573/8f204212-8645-465d-a1ec-8f80e159692f)

Looks like some fish shenanigans.

Related: #99

Events:

1. My default shell is fish.
2. I ssh into a remote machine.
3. I press <kbd>control</kbd> <kbd>shift</kbd> <kbd>h</kbd>
4. I see a blank screen, a flash of the screen attached above, and a blank screen, and it quits the preview.

video: 

https://github.com/mikesmithgh/kitty-scrollback.nvim/assets/84777573/a24bb924-88d2-4aba-a2c1-738f8c95b9de

Versions:
- Kitty: 0.33.1
- Nvim: v0.10.0-dev-2677+g2c1e8f7e9-Homebrew
- kitty-scrollback.nvim: v4.2.3 commit 3d66a2b

**Comment by mikesmithgh** [comment] 2024-04-05 01:58
Hi @SichangHe thank you for reporting. I was able to reproduce this with bash so it does not appear to be a fish specific issue. I think I discovered the root cause of an incorrect cwd when over ssh. Could you test with branch [fix-cwd-root](https://github.com/mikesmithgh/kitty-scrollback.nvim/tree/fix-cwd-root) and let me know if it works for you?

This was a tricky one, thanks for the detailed info 👍 .

**Comment by SichangHe** [comment] 2024-04-05 04:05
Can confirm `fix-cwd-root` works with my setup 🎉 .

Thank you for the super quick reaction and fix ❤️ !

**Comment by mikesmithgh** [comment] 2024-04-05 11:59
awesome, merged to main [v4.3.1](https://github.com/mikesmithgh/kitty-scrollback.nvim/releases/tag/v4.3.1) via #222

**Closed by mikesmithgh** 2024-04-05 11:59 UTC
Labels: bug

**Comment by SichangHe** [comment] 2024-04-05 12:09
🎉
